FROM python:3.12-slim
RUN useradd -ms /bin/bash vulnuser
USER vulnuser
WORKDIR /home/vulnuser/app
COPY --chown=vulnuser:vulnuser . .
RUN apt-get update && apt-get install -y build-essential gcc g++ && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r requirements.txt
ENV MODEL_PATH="/home/vulnuser/app/models"
ENTRYPOINT ["python", "analyzer.py"]